### PR TITLE
Implemented jump search strategy

### PR DESCRIPTION
**Pull request by msultan**
This PR implements a jump search strategy method allowing parameters to be sampled with a particular jump. Its basically a small wrapper around the enumerate method thats already there .

### CODE REVIEW

**Comment by mpharrigan** [comment]
You could name it `step` for consistency with `range()`

https://docs.python.org/3.4/library/functions.html#func-range

(or not)

**Comment by msultan** [comment]
alright here is what i think should be a basic use. Does the naming make sense now @mpharrigan ? 

```
estimator:
  entry_point: sklearn.svm.SVC

strategy:
  name: hyperopt_tpe

search_space:
  C:
    min: 1
    max: 10
    type: jump
    step: 4

cv: 5

dataset_loader:
  name: sklearn_dataset
  params:
    method: load_digits

trials:
    uri: sqlite:///osprey-trials.db
```


```python
In [8]: from osprey.config import Config

In [9]: c = Config("test.yaml")
Loading config file:     test.yaml...

In [10]: c.search_space()
Out[10]: 
Hyperparameter search space:
  C                        	(enum)    choices = (1.0, 5.0, 9.0)

In [11]: 

````

**Comment by mpharrigan** [comment]
:100:

**Comment by rmcgibbo** [comment]
Nice gif.

**Pull request merged**
