### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by cxhernandez**
update from legacy (see https://github.com/pandegroup/osprey/issues/86)

### CODE REVIEW

**Comment by cxhernandez** [comment]
@rmcgibbo: do we really need a flake8 test?

**Comment by rmcgibbo** [comment]
:)

**Comment by mpharrigan** [comment]
Obviously we do, or we'd be infected with the **blight** that is spaceless commas

**Comment by rmcgibbo** [comment]
Let's add more flake8 tests to other repos.

**Comment by cxhernandez** [comment]
🙄

**Pull request merged**
