### PR TITLE
 implemented currentbest command

### PR DESCRIPTION
**Pull request by msultan**
This PR implements the current_best model command in the set of cli and prints out the parameters that go with the model. 

```
$ osprey current_best -h 
usage: osprey current_best [-h] config

Get paramters for the current best model

positional arguments:
  config      Path to worker config file (yaml)

optional arguments:
  -h, --help  show this help message and exit
```
And the output 
```
$ osprey current_best config_80ns_prefeat.yaml 
Best Current Model  = 5.984363+-0.004689
PipelineStep	Paramter 	 Value
tica
		 gamma 	 1.44140916312e-06
		 lag_time 	 7
		 n_components 	 13
		 weighted_transform 	 True
cluster
		 batch_size 	 100
		 compute_labels 	 True
		 init 	 k-means++
		 init_size 	 None
		 max_iter 	 100
		 max_no_improvement 	 10
		 n_clusters 	 375
		 n_init 	 3
		 random_state 	 None
		 reassignment_ratio 	 0.01
		 tol 	 0.0
		 verbose 	 0
msm
		 ergodic_cutoff 	 on
		 lag_time 	 4
		 n_timescales 	 5
		 prior_counts 	 0
		 reversible_type 	 mle
		 sliding_window 	 True
		 verbose 	 False

```

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Good idea.

**Comment by msultan** [comment]
give me a few to fix the pep8 issues

**Comment by msultan** [comment]
hmm, dont know why its failing now. The logs say that it cant seem to find ```_check_cv``` in 3 of the 4 builds.

**Comment by rmcgibbo** [comment]
Probably that function doesn't exist in the latest sklearn release.

**Comment by msultan** [comment]
Can we merge this too or do i need to push a newer version ?

**Pull request merged**
